### ISSUE TITLE
HACS doesnt work

### ISSUE THREAD

**Issue by johro897** [akeslo/ouraring-ha#3]
Since last release "synced v1" hacs is not working. It gives an unknown error when trying to open it in hacs and trying to update renders nothing.

This means I have ended in a catch 22, I cant update and I cant remove.

**Comment by akeslo** [comment]
@johro897 yeah, sorry - not intended.  @nitobuendia has now integrated the v2 API into the original code. I've ported everything I use back.  The original repo does not have HACS support - not sure why.  My plan is to sync this repo with the original and maintain the HACS support.  This way, it's not a manual process when @nitobuendia commits changes.

Note though, this is a breaking change.  Remain at v1.1 if you are setup and working as you'd like, I just don't plan to make any changes to that code as there is no longer a need.

If you port back over to @nitobuendia and run into any issues lmk. Hopefully I'll have HACS working via this repo shortly.

**Comment by akeslo** [comment]
@johro897 the sync I mentioned above is setup now.  Upgrade via HACS to Syncedv1.0 will give you the latest code available at https://github.com/nitobuendia/oura-custom-component.  The main branch will sync every 1 hour (if a change was made).

Again this will break the prior config so see readme for setup instructions.

In HACS, the critical thing is that the component now lives in a different directory: oura vs ouraring. I had to reboot my HA to see this properly reflected.

![image](https://user-images.githubusercontent.com/3003773/213944911-ce082089-9dbd-4215-8f6d-ace9f4ef7a24.png)

Let me know if this works on your side / is helpful to maintain.

**Comment by nitobuendia** [comment]
`The original repo does not have HACS support - not sure why`

[It had](https://community.home-assistant.io/t/custom-componenet-oura-ring-sleep-data-sensor/130616/19?u=nitobuendia). Captured the progress and [rationale to revert it here](https://github.com/nitobuendia/oura-custom-component/issues/1). This is related to [this](https://community.home-assistant.io/t/the-future-of-yaml/186879), [my response](https://community.home-assistant.io/t/request-to-bring-back-yaml-arguments-against-the-future-of-yaml/205218/1) and the treatement I got there.

If I could prevent the component (or its forks) from being on HACS, I would, but I can't since it's open source.

**Comment by akeslo** [comment]
> `The original repo does not have HACS support - not sure why`
> 
> [It had](https://community.home-assistant.io/t/custom-componenet-oura-ring-sleep-data-sensor/130616/19?u=nitobuendia). Captured the progress and [rationale to revert it here](https://github.com/nitobuendia/oura-custom-component/issues/1). This is related to [this](https://community.home-assistant.io/t/the-future-of-yaml/186879), [my response](https://community.home-assistant.io/t/request-to-bring-back-yaml-arguments-against-the-future-of-yaml/205218/1) and the treatement I got there.
> 
> If I could prevent the component (or its forks) from being on HACS, I would, but I can't since it's open source.

Interesting...thanks for sharing @nitobuendia
